* venv : torch1_13

In [6]:
import numpy as np
import torch
import random

In [2]:
SEED = 0

In [9]:
# seed設定
def fix_seed(seed_value=0):
    random.seed(SEED)
    np.random.seed(SEED)
    torch.manual_seed(SEED)
    if torch.cuda.is_available():
        torch.cuda.manual_seed(SEED)
        torch.cuda.manual_seed_all(SEED)
        torch.backends.cudnn.deterministic = True
    if torch.backends.mps.is_available():
        # 特に設定のメソッドなし
        pass

In [10]:
fix_seed(SEED)

torch.randn(2,3)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])

In [11]:
torch.randn(2,3)

tensor([[ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820]])

In [12]:
fix_seed(SEED)

torch.randn(2,3)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])