In [1]:
import numpy as np

In [2]:
# 型変換
a = np.array([1.0,2.3,4.567])
print('before')
print(a)
print(a.dtype)
b = a.astype(np.uint8)
print('after')
print(b)
print(b.dtype)

before
[1.    2.3   4.567]
float64
after
[1 2 4]
uint8


In [3]:
# トップ4こを求める
a = np.array([6,4,1,8,7,3,2,9,8,10,2,3])
b = np.sort(a)
b[-4:] # np.mean([-4:]) のようにすれば平均を求められる

array([ 8,  8,  9, 10])